{
    "name": "Demo Portal",
    "category": "Uncategorized",
    "version": "18.0.1.0.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": [
        "mail",
        "portal",
        "website",
        "web_timeline",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/demo_portal_guide_data.xml",
        "views/demo_portal_help_views.xml",
        "views/demo_model_2_portal.xml",
        "views/demo_portal_templates.xml",
        "views/demo_model_3_portal_diagram.xml",
        "views/demo_model_portal.xml",
        "views/menu.xml",
        "views/snippets.xml",
    ],
    "web.assets_frontend": ["demo_portal/static/src/js/portal.demo_portal.js"],
    "website.assets_frontend": [
        "demo_portal/static/src/js/website.demo_portal.animation.js",
        "demo_portal/static/src/scss/demo_portal.scss",
    ],
    "installable": True,
    "post_init_hook": "post_init_hook",
}
